const articulos = [
  {
    id: 1,
    producto: "Arenero",
    color: "Azul",
    tamaño: "mediano",
    precio: 400,
    imagen: "./imagenes/areneropremium.webp",
    stock: true,
  },
  {
    id: 2,
    producto: "Arena Scoop Away",
    color: "morado",
    tamaño: "grande",
    precio: 800,
    imagen: "./imagenes/arenascoop.jpeg",
    stock: true,
  },
  {
    id: 3,
    producto: "Alimento Minino Plus",
    color: "verde",
    tamaño: "chico",
    precio: 160,
    imagen: "./imagenes/mininoplus.jpeg",
    stock: true,
  },
  {
    id: 4,
    producto: "Rascador Premium",
    color: "café",
    tamaño: "mediano",
    precio: 700,
    imagen: "./imagenes/rascadorpremium.jpeg",
    stock: true,
  },

  {
    id: 5,
    producto: "Rascador Premium",
    color: "café",
    tamaño: "mediano",
    precio: 700,
    imagen: "./imagenes/rascadorpremium.jpeg",
    stock: true,
  },

  {
    id: 6,
    producto: "Jueguetes",
    color: "café",
    tamaño: "mediano",
    precio: 700,
    imagen: "./imagenes/rascadorpremium.jpeg",
    stock: true,
  },

  {
    id: 7,
    producto: "Cama gatito",
    color: "café",
    tamaño: "mediano",
    precio: 700,
    imagen: "./imagenes/rascadorpremium.jpeg",
    stock: true,
  },

  {
    id: 8,
    producto: "Catnip",
    color: "café",
    tamaño: "mediano",
    precio: 700,
    imagen: "./imagenes/rascadorpremium.jpeg",
    stock: true,
  },
];
